# Generated by Django 5.1.1 on 2024-09-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='skills',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
